id: P010797
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG10778
  title: རྡོ་རྗེ་ཕག་མོའི་ཟབ་ཁྲིད། ༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  volumes:
    0a6909eec29244f9b0b71f473fcaa6b8:
      image_group_id: I1KG10804
      title: ''
      volume_number: 1
      total_pages: 748
      base_file: v001.txt
