id: IE584CBE6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:32:12+00:00'
last_modified: '2022-06-08T17:35:49.992374+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10778
  title: རྡོ་རྗེ་ཕག་མོའི་ཟབ་ཁྲིད། ༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E5C9:
      image_group_id: I1KG10804
      title: ''
      total_pages: 748
      order: 1
      base_file: E5C9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
